### ISSUE TITLE
130 char long public key

### ISSUE THREAD

**Issue by etienneroudeix** [Bit-Wasp/secp256k1-php#107]
Hi,
I'm using `secp256k1_ec_pubkey_serialize` to recover serialized public key from public key.
However it return me a 130 char long public key.
And the expected public key is the 128 right characters. I have no idea why my result is prefixed with a `0x04`.
For the moment I went ahead by ignoring those 2 chars but I really want to unterstand why I got this.
Cheers,

**Comment by afk11** [comment]
Hi

secp256k1 field elements are 32 bytes, so 64 bytes each in hex. However, they come with an extra byte of prefix, indicating what form the key is. 

there are 5 prefixes supported by bitcoin:
 \x04 - an uncompressed key, (1 + 32 + 32 => 130 hex) prefix + x and y coordinate
 \x02 + \x03 - compressed key, (1 + 32 => 66) prefix (including compression bit) and the x coordinate
 \x06 + \x07 - hybrid compressed key, (1 + 32 => 66) prefix (including compression bit) and the x coordinate

The first three are commonly used, and the prefix is part of the hashed value. However, there may be schemes which omit the prefix because a specification dictates the full x+y point must be sent. 

But for this library, it is correct to include the prefix.

**Comment by etienneroudeix** [comment]
Hi @afk11 thank you very much for your answer. All is clear now !
