### ISSUE TITLE
Talk to bitcoin core?

### ISSUE THREAD

**Issue by flip111** [Bit-Wasp/secp256k1-php#20]
I saw that at the moment PHP can only communicate over JSON RPC to bitcoin core. Also no push notifications are supported. For node.js there seem to be bindings https://github.com/bitpay/bitcore-node Could this extension provide similar functionality? An example of a notifcation would be a transaction getting verified.

**Comment by afk11** [comment]
This is a PHP extension, it wraps the upstream libsecp256k1. Its a fast elliptic curve library. Please see https://github.com/bitcoin/secp256k1. 

https://github.com/Bit-Wasp/bitcoin-php < general bitcoin library. No networking besides RPC stuff. 
https://github.com/Bit-Wasp/bitcoin-p2p-php < peer to peer network. still very early in construction. 
https://github.com/Bit-Wasp/libbitcoinconsenus-php < extension wrapping libbitcoinconsensus for script validation. 

I'm starting to think that I should remove the BitWasp\Bitcoin\Networking\Node class - making bitcoin-p2p-php just the library. Implementations should go elsewhere. 

You'll notice that the p2p framework uses ReactPHP - so it's event driven rather like bitcore-node. 

It' still early days, so I can't advise you to build your app around this - but check out the repo's and let me know what you think.

**Comment by flip111** [comment]
_BitWasp\Bitcoin\Networking\Node class_ not sure where to find this. The fact that you are using ReactPHP is really nice. Though i was specifically looking for a solution to have push notifications originating from bitcoin core. I was wondering if your extension C code directly talk to bitcoin core. I saw people are working on PR to make this possible through ZeroMQ ... this looks really promising.

As i understand you are implementing functionality found in bitcoin core with php? Or are you creating an SPV? Right now i don't have enough background knowledge on the bitcoin ecosystem to really evaluate the libraries properly.

**Comment by rubensayshi** [comment]
@flip111 the ZeroMQ thing indeed looks promising, but it's still not merged and ZeroMQ is not the easiest thing in the world (of PHP).

Another option is using the `importaddress` RPC command of bitcoin core, which imports addresses into the wallet of bitcoin core, as watch-only.  
Together with the `walletnotify` config to trigger a certain command when events happen (the command being running one of your PHP scripts.
`walletnotify` triggers on; first receiving a payment, first conformation on the payment, you send a payment.  
if you want to wait for > 1 confirmation you'd have to add `blocknotify` too because `walletnotify` only triggers on the first confirmation.

The last option is to run a P2P node (we personally use bitcore-node, but you could also try bitcoin-p2p-php) and then push transactions into a queue and process those, but of the above options that requires the most knowledge of how bitcoin works and the most coding etc.

and a shameful plug; I'm CTO @ Blocktrail, Bitcoin Developers Platform, we provide 'webhooks' where you can subscribe to events for addresses or you can even create a wallet with our PHP SDK and be notified for anything that happens on that wallet.  
there's also other competitors that provide the same service, such as chain.com, blockcypher.com.  
they also have solid infrastructure for webhooks and I feel that if you're relatively new to bitcoin this might make your life a lot easier.

**Comment by afk11** [comment]
At that, the ZMP PR (bitcoin/bitcoin #

**Comment by afk11** [comment]
@flip111: If you're very new to this, an API is probably the best way to go. Maybe have a look over the repo's (now all listed here: https://github.com/Bit-Wasp/bitcoin-php) and let us know what messages you're looking for.

**Comment by afk11** [comment]
FYI - bitcore-node alludes to what you mentioned first: https://github.com/bitpay/bitcore-node/blob/master/docs/patch.md
